-- MySQL Script generated by MySQL Workbench
-- Tue Dec 17 20:56:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock-market-charting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock-market-charting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock-market-charting` DEFAULT CHARACTER SET utf8 ;
USE `stock-market-charting` ;

-- -----------------------------------------------------
-- Table `stock-market-charting`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`role` (
  `ro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ro_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`user` (
  `us_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(75) NULL DEFAULT NULL ,
  `us_password` VARCHAR(255) NULL DEFAULT NULL,
  `us_email` VARCHAR(50) NULL DEFAULT NULL,
  `us_mobile_number` VARCHAR(45) NULL DEFAULT NULL,
  `us_confirmed` BOOLEAN NULL DEFAULT NULL,
  `us_ro_id` INT(11) NOT NULL,
  PRIMARY KEY (`us_id`, `us_ro_id`),
  INDEX `fk_user_role_idx` (`us_ro_id` ASC),
  UNIQUE INDEX `us_name_UNIQUE` (`us_name` ASC),
  CONSTRAINT `fk_us_ro`
    FOREIGN KEY (`us_ro_id`)
    REFERENCES `stock-market-charting`.`role` (`ro_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`sectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`sectors` (
  `sc_id` BIGINT(10) NOT NULL,
  `sc_name` VARCHAR(255) NULL DEFAULT NULL,
  `sc_brief` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`sc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`IPO_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`ipo_details` (
  `ipo_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `ipo_company_name` VARCHAR(255) NULL DEFAULT NULL,
  `ipo_stock_exchange` VARCHAR(255) NULL DEFAULT NULL,
  `ipo_price_per_share` BIGINT(10) NULL DEFAULT NULL,
  `ipo_total_no_of_share` BIGINT(10) NULL DEFAULT NULL,
  `ipo_open_date` DATETIME NULL DEFAULT NULL,
  `ipo_remarks` VARCHAR(255) NULL DEFAULT NULL,
  `ipo_active` BOOLEAN NULL DEFAULT NULL,
  PRIMARY KEY (`ipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`company` (
  `co_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `co_name` VARCHAR(255) NULL DEFAULT NULL,
  `co_turnover` FLOAT NULL DEFAULT NULL,
  `co_sc_id` BIGINT(10) NOT NULL,
  `co_ceo` VARCHAR(255) NULL DEFAULT NULL,
  `co_board_of_directors` VARCHAR(255) NULL DEFAULT NULL,
  `co_brief_writeup` VARCHAR(255) NULL DEFAULT NULL,
  `co_active` BOOLEAN NULL DEFAULT NULL,
  `co_stock_code` BIGINT(10) NULL DEFAULT NULL,
  `co_ipo_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`co_id`),
  INDEX `fk_company_sectors1_idx` (`co_sc_id` ASC),
  UNIQUE INDEX `co_name_UNIQUE` (`co_name` ASC),
  INDEX `fk_company_ipo_details1_idx` (`co_ipo_id` ASC),
  CONSTRAINT `fk_company_sectors1`
    FOREIGN KEY (`co_sc_id`)
    REFERENCES `stock-market-charting`.`sectors` (`sc_id`),
  CONSTRAINT `fk_company_ipo_details1`
    FOREIGN KEY (`co_ipo_id`)
    REFERENCES `stock-market-charting`.`ipo_details` (`ipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`stock_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`stock_price` (
  `sp_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `sp_company_code` BIGINT(10) NULL,
  `sp_stock_exchange` VARCHAR(255) NULL DEFAULT NULL,
  `sp_current_price` float NULL DEFAULT NULL,
  `sp_date` DATE NULL DEFAULT NULL,
  `sp_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`sp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`stock_exchange` (
  `se_id` BIGINT(10) NOT NULL,
  `se_stock_exchange` VARCHAR(50) NOT NULL,
  `se_brief` VARCHAR(255) NULL DEFAULT NULL,
  `se_contact_address` VARCHAR(255) NULL DEFAULT NULL,
  `se_remarks` VARCHAR(45) NULL DEFAULT NULL,
  `se_active` BOOLEAN NULL DEFAULT NULL,
  PRIMARY KEY (`se_id`),
  UNIQUE INDEX `se_stock_exchange_UNIQUE` (`se_stock_exchange` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`company_stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`company_stock_exchange` (
  `cs_co_id` BIGINT(10) NOT NULL,
  `cs_se_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`cs_co_id`, `cs_se_id`),
  INDEX `fk_company_has_stock_exchange_stock_exchange1_idx` (`cs_se_id` ASC),
  INDEX `fk_company_has_stock_exchange_company1_idx` (`cs_co_id` ASC),
  CONSTRAINT `fk_company_has_stock_exchange_company1`
    FOREIGN KEY (`cs_co_id`)
    REFERENCES `stock-market-charting`.`company` (`co_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_has_stock_exchange_stock_exchange1`
    FOREIGN KEY (`cs_se_id`)
    REFERENCES `stock-market-charting`.`stock_exchange` (`se_id`)	
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `stock-market-charting`.`role` (`ro_id`, `ro_type`) VALUES ('1', 'ADMIN');
INSERT INTO `stock-market-charting`.`role` (`ro_id`, `ro_type`) VALUES ('2', 'USER');

INSERT INTO `stock-market-charting`.`user` (`us_id`, `us_name`, `us_password`, `us_email`, `us_mobile_number`, `us_confirmed`, `us_ro_id`) VALUES ('1', 'admin', '$2a$10$SZ/GoSeV/wluF6AfG2VXB.Q2AYlLBxYc8sbSS/9nFfkfVv/U3Odtm', 'admin@gmail.com', '9876543210', 1, 1);

INSERT INTO `stock-market-charting`.`stock_exchange` (`se_id`, `se_stock_exchange`, `se_brief`, `se_contact_address`, `se_remarks`, `se_active`) VALUES ('1', 'BSE', 'BOMBAY STOCK EXCHANGE', 'BSE,Mumbai,India', 'Best in India', '1');
INSERT INTO `stock-market-charting`.`stock_exchange` (`se_id`, `se_stock_exchange`, `se_brief`, `se_contact_address`, `se_remarks`, `se_active`) VALUES ('2', 'NSE', 'NATIONAL STOCK EXCHANGE', 'NSE,Delhi,India', 'NIFTY', '1');

INSERT INTO `stock-market-charting`.`sectors` (`sc_id`, `sc_name`, `sc_brief`) VALUES ('1', 'Insurance', 'Policies');
INSERT INTO `stock-market-charting`.`sectors` (`sc_id`, `sc_name`, `sc_brief`) VALUES ('2', 'Oil&Natural Gas', 'Resources');
INSERT INTO `stock-market-charting`.`sectors` (`sc_id`, `sc_name`, `sc_brief`) VALUES ('3', 'Construction', 'Infrastructure');
INSERT INTO `stock-market-charting`.`sectors` (`sc_id`, `sc_name`, `sc_brief`) VALUES ('4', 'Banking', 'Domestic & Industrial');
INSERT INTO `stock-market-charting`.`sectors` (`sc_id`, `sc_name`, `sc_brief`) VALUES ('5', 'Food Processing', 'Food Production');

INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('1', 'ITC', 'BSE', '1000', '100', '2018-01-12', 'private', '1');
INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('2', 'ASV', 'NSE', '2000', '50', '2017-11-05', 'private', '1');
INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('3', 'ONGC', 'NSE', '5000', '1000', '2015-06-11', 'govenment', '0');
INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('4', 'AIG', 'BSE', '100', '500', '2019-04-05', 'private', '1');
INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('5', 'HDFC', 'BSE', '1300', '6000', '2014-06-18', 'private', '0');
INSERT INTO `stock-market-charting`.`ipo_details` (`ipo_id`, `ipo_company_name`, `ipo_stock_exchange`, `ipo_price_per_share`, `ipo_total_no_of_share`, `ipo_open_date`, `ipo_remarks`, `ipo_active`) VALUES ('6', 'YES Bank', 'NSE', '500', '5005', '2017-11-15', 'private', '1');

INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('1', 'ITC', '100000', '5', 'Sanjiv Puri', 'Sanjiv Puri', 'Produces Biscuits,Chips', '1', '1', '500112');
INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('2', 'ASV', '50000', '3', 'Vaibhav Kamdar', 'Vaibhav Kamdar', 'Construction', '1', '2', '500113');
INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('3', 'ONGC', '120000', '2', 'Shashi Shanker', 'Shashi Shanker', 'Oil and LPG', '1', '3', '3');
INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('4', 'AIG', '150000', '1', 'Brian Duperreault', 'Brian Duperreault', 'Insurance', '1', '4', '500105');
INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('5', 'HDFC', '500000', '4', 'Aditya Puri', 'Aditya Puri', 'Banking', '1', '5', '4');
INSERT INTO `stock-market-charting`.`company` (`co_id`, `co_name`, `co_turnover`, `co_sc_id`, `co_ceo`, `co_board_of_directors`, `co_brief_writeup`, `co_active`, `co_ipo_id`, `co_stock_code`) VALUES ('6', 'Yes', '40000', '4', 'Ravneet Gill', 'Ravneet Gill', 'Banking', '0', '6', '5');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
